name: CI/CD

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  test:
    runs-on: windows

    steps:
    - uses: actions/checkout@v3
  
    - uses: actions/setup-java@v3
      with:
        java-version: '18'
        distribution: "adopt"

    - name: Gradle Test
      run: |
        ./gradlew test
